-- CreateTable
CREATE TABLE `REPORTEAVANCE` (
    `avance_id` INTEGER NOT NULL AUTO_INCREMENT,
    `act_id` INTEGER NOT NULL,
    `asunto` VARCHAR(191) NOT NULL,
    `descripcion` VARCHAR(191) NOT NULL,
    `archivo` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`avance_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `REPORTEAVANCE` ADD CONSTRAINT `REPORTEAVANCE_act_id_fkey` FOREIGN KEY (`act_id`) REFERENCES `ACTIVIDAD`(`act_id`) ON DELETE CASCADE ON UPDATE CASCADE;
