-- CreateTable
CREATE TABLE `EJEESTRATEGICO` (
    `eje_id` INTEGER NOT NULL AUTO_INCREMENT,
    `nombre_eje` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`eje_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
